### ISSUE TITLE
[Bug]: Ueransim Values not available and helm not working properly

### ISSUE THREAD

**Issue by rodrigosanzsanz** [Gradiant/5g-charts#156]
### Steps to reproduce

Hello,

The helm ueransim and values used to work properly but right now the values info can not be reached. Maybe any change of name or location?

![image](https://github.com/Gradiant/5g-charts/assets/133344742/7041d0d2-5f27-4a40-a004-67aeb822ad0a)

Could you take a view? I am checking any workaround

Regards. Thanks

### Logs

```shell
NA
```

### Expected behaviour

No error and ueransim normal up in K8,

### Observed Behaviour

Get values from url like documentation indicates.

**Comment by rodrigosanzsanz** [comment]
After review , the documentation is not availabler. Loading data with a file it seems no issues.

**Comment by mmarquez999** [comment]
Hi @rodrigosanzsanz,

This is due to the fact that we are currently working on updating the documentation of the repository, since we have changed the name of repository recently. 

Hopefully this issue will be fixed very soon and the documentation will be available again!

Sorry for the inconveniences!

**Comment by mmarquez999** [comment]
Hello again @rodrigosanzsanz,

The documentation has been properly updated, so the tutorials found in https://gradiant.github.io/5g-charts/ and the corresponding links should be working now. 

Hopefully you can try it again now!

**Comment by rodrigosanzsanz** [comment]
Sure!! I was checking the new docs!!! Thanks!!
