### ISSUE TITLE
How to create 100 UE's in open5gs

### ISSUE THREAD

**Issue by chethantk** [Gradiant/5g-charts#176]
If we incease the count of UE's from 2 to 100 ,The uesimtun is not creating

Here are the logs from AMF and gnb

![image](https://github.com/Gradiant/5g-charts/assets/65939021/45018811-a3e8-4e4f-90fe-2598ef96330a)

![image](https://github.com/Gradiant/5g-charts/assets/65939021/52022ea2-5f04-430c-9630-01c1b6d2b399)

Can anybody help on this to create Number of UE's in UERANSIM

Attached the gnb-ues yaml file also 

![image](https://github.com/Gradiant/5g-charts/assets/65939021/0675b193-bb34-494e-93cc-caf4e628f043)

Can anybody help on this to create Number of UE's in UERANSIM

**Comment by avrodriguezgrad** [comment]
Hi @chethantk 

Your problem is not about the amount of UE's. You are having a problem regarding Network slicing configuration. 

Which slices have you defined in the AMF and NSSF configuration of Open5GS? You must have the same as gnb-ues-values.yaml file, which is sst: 1 and sd: 0x111111.

BR,
Álvaro
